AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  S3FCRoleArn:
    Type: String
    Description: "Role used by S3FC."
  ExternalId:
    Type: String
    Description: "External ID Passed by S3FC."


Resources:

  ExampleJobKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Example Job KMS Key
      Enabled: true
      EnableKeyRotation: false
      KeyPolicy:
        Version: '2012-10-17'
        Id: example-key-policy
        Statement:
          - Sid: 'Enable IAM User Permissions'
            Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  ExampleJobBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '-', ['example-job', !Ref 'AWS::Region', !Ref 'AWS::AccountId']]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref ExampleJobKey
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: 'App'
          Value: ExampleJob
      VersioningConfiguration:
        Status: Enabled

  JobDataRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: example-job-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Ref S3FCRoleArn
          Action: sts:AssumeRole
          Condition:
            StringEquals:
              "sts:ExternalId":
                - !Ref ExternalId
      Policies:
      - PolicyName: S3Access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: S3List
            Effect: Allow
            Action: s3:ListBucket
            Resource: !GetAtt ExampleJobBucket.Arn
            Condition:
                StringEquals: 
                    "s3:prefix": 
                        - "example-source-data"
          - Sid: S3Read
            Effect: Allow
            Action: s3:GetObject
            Resource:
            - !Join [ "", [ !GetAtt ExampleJobBucket.Arn, "/example-source-data/*" ] ]
          - Sid: S3Write
            Effect: Allow
            Action: s3:PutObject
            Resource:
            - !Join [ "", [ !GetAtt ExampleJobBucket.Arn, "/example-destination-data/*" ] ]
      - PolicyName: KMSKeyAccess
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            Effect: Allow
            Action:
            - kms:Encrypt
            - kms:Decrypt
            - kms:GenerateDataKey
            - kms:DescribeKey
            Resource: !GetAtt ExampleJobKey.Arn

Outputs:
  ExampleJobDataRole:
    Description: "Example Job ARN"
    Value: !GetAtt JobDataRole.Arn
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", ExampleJobDataRole ] ]

  ExampleBucket:
    Description: "Example Job ARN"
    Value: !GetAtt ExampleJobBucket.Arn
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", ExampleBucket ] ]

  ExampleBucketName:
    Description: "Example Job NAME"
    Value: !Ref ExampleJobBucket
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", ExampleBucketName ] ]
